version: '3.8'
services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.5
    container_name: redpanda-1
    networks:
      - car-net
    ports:
      - "9092:9092"  # Kafka Port
      - "8081:8081"  # Redpanda Console Port
    command: redpanda start --advertise-kafka-addr redpanda-1:9092

  database:
    image: postgres:15
    container_name: car-db
    networks:
      - car-net
    environment:
      POSTGRES_USER: car_user
      POSTGRES_PASSWORD: car_pass
      POSTGRES_DB: car_db
    ports:
      - "5432:5432"

  car-backend:
    build:
      context: ./car-backend
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: car-backend
    networks:
      - car-net
    depends_on:
      - database
      - redpanda
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda-1:9092
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://database:5432/car_db
      QUARKUS_DATASOURCE_USERNAME: car_user
      QUARKUS_DATASOURCE_PASSWORD: car_pass
    ports:
      - "8080:8080"

  text-validation:
    build:
      context: ./text-validation-service
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: text-validation
    networks:
      - car-net
    depends_on:
      - redpanda
    environment:
      KAFKA_BOOTSTRAP_SERVERS: redpanda-1:9092
    ports:
      - "8082:8080"

networks:
  car-net:
    driver: bridge