name: JMeter Load Test

on:
  workflow_dispatch:

jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download JMeter
        run: |
          wget https://downloads.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
          tar -xvzf apache-jmeter-5.6.2.tgz

      - name: Run JMeter Test
        run: |
          apache-jmeter-5.6.2/bin/jmeter -n -t src\test\java\com\example\jmeter\car-loadtest.jmx -l reports/jmeter/results.jtl -e -o src\test\java\com\example\reports\jmeter

      - name: Upload JMeter Report
        uses: actions/upload-artifact@v3
        with:
          name: jmeter-html-report
          path: reports/jmeter/html-report